image: openjdk:8

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x gradlew
  script:
    -


stages:
  - publishReport