image: openjdk:8

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

publishReport:
  stage: publish
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x gradlew
  script:
    - ./gradlew run --args="cemba.conf 404659530"


stages:
  - publish